### ISSUE TITLE
Faktury MD

### ISSUE THREAD

**Issue by 61Stan** [eurosecom/eurosecom#190]
Zoznam faktúr v podsystéme účtovníctvo.

### Todo ###
- [x] Formátovanie zoznamu
- [ ] **Vyhľadávanie** v zozname @eurosecom

**Comment by eurosecom** [comment]
- sysx=UCT&rozuct=ANO, treba aj pri stránkovaní 
- stránkovanie mi funguje

**Comment by eurosecom** [comment]
- každý  mesiac je viac xml faktúr a viac orange faktúr, nie je len jedna za mesiac

**Comment by 61Stan** [comment]
Pýtal som sa na obmedzenie ako je napr. pri tlači = som prepnutý v 3.2017, tak len tlačím 3.2017. To isté aj v importe = som v 3.2017 a importujem len .xml za 3.2017.

**Comment by eurosecom** [comment]
- pri nahrávaní faktúry z XML nastavené ume nie je zaujímavé tak ako pri nahrávaní z papiera

**Comment by eurosecom** [comment]
- pri načítaní originálu dokladu zatiaľ asi ano aj  .gif a .bmp, nemáme info o tom čo kto používa
- druhy dokladov asi neblokovať, narýchlo ma napadá, že to je spoločné aj pre odbyt, ak chce niekto len jednu analytiku ale nie 31100 ale 31101 a jednoduché číslovanie tak by sa to nedalo riešiť...
- možno by sa to dalo opačne, zrušiť číslovanie v parametroch účta a obsluhovať ho z druhov, museli by sme pridať druhy všeob

**Comment by 61Stan** [comment]
- .gif a .bmp by som zrušil: reálne nasadenie nového vzhľadu beh na dlhé trate. Namiesto .gif a .bmp môžu použiť .jpg alebo .png. Keď sa niekto ozve, tak budeme riešiť. Ja by som sa vydal cestou osekať veci, ktoré nie sú často (?) používané a zameral sa na hlavné veci a tie zlepšoval, napr. import faktúr / orange by som riešil priamo vo faktúrach cez modal, ako som plánoval s výberom firmy v hlavnom menu. Ide o to, aby užívateľ čo najmenej dával tam a spať a strácal focus. V podstate aby čo najmenej musel klikať medzi oknami a pamätal si, kde čo je.
- zrušenie číslovania v parametroch = to je vianočný darček. Min. pol roka som do Vás rýpal, aby sme zjednotili číslovanie a Vy nie. A teraz to spomeniete. Keď to myslíte vážne. Tak jednoznačne preč z parametrov. Aj keď reálny dopad moc veľký nebude, pretože všetky firmy už majú nastavené a neviem si predstaviť, ako by sa prehadzovalo.
- s vyhľadávaním ešte neviem. Najjednoduchšie jeden vysúvací input a cez neho všetko vyhľadávať. Ale sú tam šipky pre preklikávanie mesiacov. Napadlo ma, že pri preklikávaní bude mesiac vypisovať pod text "DAT/UME" v záhlaví stĺpca

**Comment by 61Stan** [comment]
### Skúšam ###
### Task ###
- [ ] funkčné alerty po vymazaní / upravení faktúry @eurosecom 
- [ ] grafické doladenie zoznamu

**Comment by 61Stan** [comment]
- [x] Formátovanie zoznamu

**Comment by 61Stan** [comment]
- [ ]

**Comment by 61Stan** [comment]
### Todo ###
- [x] Formátovanie zoznamu
- [ ] **Vyhľadávanie** v zozname @eurosecom

**Comment by 61Stan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zoznam faktúr](https://trello.com/c/ebbZyyaB/14-zoznam-fakt%C3%BAr)
